# Generated by Django 5.0.1 on 2025-08-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
