# Generated by Django 5.0.1 on 2025-09-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_property_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('broker', 'Through Broker')], default='direct', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=20, unique=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.broker')),
            ],
        ),
    ]
