# Generated by Django 5.0.1 on 2025-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_property_source_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='broker_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
