# Generated by Django 5.0.1 on 2025-09-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_broker_broker_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='broker_code',
            new_name='code',
        ),
    ]
