# Generated by Django 5.0.1 on 2025-09-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_broker_code_broker_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='code',
            new_name='broker_code',
        ),
    ]
