# Generated by Django 5.0.1 on 2025-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_broker_broker_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
