# Generated by Django 5.0.1 on 2025-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20250916_1906'),
    ]

    operations = [
        
    ]
