# Generated by Django 5.0.1 on 2025-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20250916_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
