# Generated by Django 5.0.1 on 2025-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_broker_broker_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
